"""Deterministic USPS-style formatting used for Census address lookups.

The tables below are a checked-in transcription of the USPS Publication 28
Appendix C1 (street suffixes) and C2 (secondary unit designators) standard
abbreviations.  They intentionally do not validate or correct an address.
"""

import re


def _table(rows: str) -> dict[str, str]:
    """Turn compact ``variants:standard`` rows into a lookup dictionary."""
    result: dict[str, str] = {}
    for row in rows.strip().splitlines():
        variants, standard = row.split(":")
        for variant in variants.split(","):
            result[variant.strip()] = standard.strip()
    return result


# Publication 28 C1.  Both the primary name and common USPS alternate forms
# are included so either source-system spelling normalizes to the USPS suffix.
STREET_SUFFIXES = _table(
    """
ALLEE,ALLEY,ALLY:ALY
ANEX,ANNEX,ANNX:ANX
ARCADE:ARC
AVENUE,AV,AVE,AVEN,AVENU,AVN,AVNUE:AVE
BAYOU,BAYOO:BYU
BEACH:BCH
BEND:BND
BLUFF,BLUF:BLF
BLUFFS:BLFS
BOTTOM,BOT,BOTTM,BOTTM:BTM
BOULEVARD,BLVD,BOUL,BOULV:BLVD
BRANCH,BRNCH:BR
BRIDGE,BRG:BRG
BROOK,BRK:BRK
BROOKS:BRKS
BURG:BG
BURGS:BGS
BYPASS,BYPAS,BYPA,BYPSS:BYP
CAMP,CMP:CP
CANYON,CANYN,CNANYN,CYN:CYN
CAPE:CPE
CAUSEWAY,CAUSWAY:CSWY
CENTER,CENT,CENTR,CNTER,CNTR,CTR:CTR
CENTERS:CTRS
CIRCLE,CIRC,CIRCL,CRCL,CRCLE:CIR
CIRCLES,CIRS:CIRS
CLIFF,CLF:CLF
CLIFFS,CLFS:CLFS
CLUB:CLB
COMMON:CMN
COMMONS:CMNS
CORNER,COR:COR
CORNERS,CORS:CORS
COURSE:CRSE
COURT,CT:CT
COURTS,CTS:CTS
COVE,CV:CV
COVES,CVS:CVS
CREEK,CR:CRK
CRESCENT,CRES,CENT,CRESNT,CRSENT,CRSNT:CRS
CREST:CRST
CROSSING,CRSSNG,XING:XING
CROSSROAD:XRD
CURVE:CURV
DALE:DL
DAM:DM
DIVIDE,DIV,DVD,DV:DV
DRIVE,DR,DRIV,DRV:DR
DRIVES,DRS:DRS
ESTATE,EST:EST
ESTATES,ESTS:ESTS
EXPRESSWAY,EXP,EXPR,EXPRESS,EXPW,EXPY:EXPY
EXTENSION,EXT,EXTN,EXTNSN:EXT
EXTENSIONS,EXTS:EXTS
FALL:FALL
FALLS,FLS:FLS
FERRY,FRRY,FRY:FRY
FIELD,FLD:FLD
FIELDS,FLDS:FLDS
FLAT,FLT:FLT
FLATS,FLTS:FLTS
FORD,FRD:FRD
FORDS,FRDS:FRDS
FOREST,FORESTS,FRST:FRST
FORGE,FORG,FRG:FRG
FORGES,FRGS:FRGS
FORK,FRK:FRK
FORKS,FRKS:FRKS
FORT,FRT,FT:FT
FREEWAY,FREEWY,FRWAY,FRWY,FWY:FWY
GARDEN,GARDN,GRDEN,GRDN:GRDN
GARDENS,GARDNS,GRDNS:GRDNS
GATEWAY,GATEWY,GATWAY,GTWAY,GTWY:GTWY
GLEN,GLN:GLN
GLENS,GLNS:GLNS
GREEN,GRN:GRN
GREENS,GRNS:GRNS
GROVE,GROV,GRV:GRV
GROVES,GRVS:GRVS
HARBOR,HARB,HARBR,HRBOR:HBR
HARBORS:HBRS
HAVEN,HVN:HVN
HEIGHTS,HT,HTS:HTS
HIGHWAY,HIGHWY,HIWAY,HIWY,HWAY,HWY:HWY
HILL,HL:HL
HILLS,HLS:HLS
HOLLOW,HOLLOWS,HOLWS:HOLW
INLET,INLT:INLT
ISLAND,IS,ISLND:IS
ISLANDS,ISLNDS:ISS
ISLE:ISLE
JUNCTION,JCTION,JCT,JUNCTN,JUNCTON:JCT
JUNCTIONS,JCTS:JCTS
KEY,KEYY:KY
KEYS,KEYS,KYS:KYS
KNOLL,KNOL:KNL
KNOLLS,KNOLS:KNLS
LAKE,LK:LK
LAKES,LKS:LKS
LAND:LAND
LANDING,LNDG,LNDNG:LDG
LANE,LN:LN
LIGHT,LGT:LT
LIGHTS,LGTS:LTS
LOAF,LF:LF
LOCK,LCK:LCK
LOCKS,LCKS:LCKS
LODGE,LDG,LDGE,LODG:LDG
LOOP,LOOPS:LOOP
MALL:MALL
MANOR,MNR:MNR
MANORS,MNRS:MNRS
MEADOW,MDW:MDW
MEADOWS,MEDOWS,MDWS:MDWS
MEWS:MEWS
MILL,ML:ML
MILLS,MLS:MLS
MISSION,MISSN,MSN:MSN
MOTORWAY,MOTORWY,MOTWAY,MWY:MTWY
MOUNT,MT,MNT:MT
MOUNTAIN,MNTN,MTIN,MTN,MOUNTIN:MTN
MOUNTAINS,MNTS:MNTS
NECK,NCK:NCK
ORCHARD,ORCH,ORCHRD:ORCH
OVAL,OVL:OVAL
OVERPASS,OVERPS:OPAS
PARK,PRK:PARK
PARKS:PARK
PARKWAY,PARKWY,PKWAY,PKWY,PKY:PKWY
PARKWAYS,PKWYS:PKWY
PASS:PASS
PASSAGE,PSGE:PSGE
PATH,PATHS:PATH
PIKE,PIKES:PIKE
PINE,PNE:PNE
PINES,PNES:PNES
PLACE,PL:PL
PLAIN,PLN:PLN
PLAINS,PLNS:PLNS
PLAZA,PLZ,PLZA:PLZ
POINT,PT:PT
POINTS,PTS:PTS
PORT,PRT:PRT
PORTS,PRTS:PRTS
PRAIRIE,PRR:PR
RADIAL,RAD,RADL,RDL:RADL
RANCH,RANCHES,RNCH,RNCHS:RNCH
RAPID,RPD:RPD
RAPIDS,RPDS:RPDS
REST,RST:RST
RIDGE,RDG,RDGE:RDG
RIDGES,RDGS:RDGS
RIVER,RIV,RIVR,RVR:RIV
ROAD,RD:RD
ROADS,RDS:RDS
ROUTE,RTE:RTE
ROW:ROW
RUE:RUE
RUN:RUN
SHOAL,SHL:SHL
SHOALS,SHLS:SHLS
SHORE,SHOAR:SHR
SHORES,SHRS:SHRS
SKYWAY,SKWY:SKWY
SPRING,SPNG,SPRNG:SPG
SPRINGS,SPNGS,SPRNGRS:SPGS
SPUR:SPUR
SPURS:SPUR
SQUARE,SQR,SQRE,SQU:SQ
SQUARES,SQRS:SQS
STATION,STA,STATN,STN:STA
STRAVENUE,STRA,STRAV,STRAVEN,STRVN,STRVNUE:STRA
STREAM,STREME,STRM:STRM
STREET,ST,STR:ST
STREETS,STS:STS
SUMMIT,SMT:SMT
TERRACE,TER,TERR:TER
THROUGHWAY,THROUGHWY,TRWY:TRWY
TRACE,TRACES,TRCE:TRCE
TRACK,TRACKS,TRAK,TRK,TRKS:TRK
TRAFFICWAY:TRFY
TRAIL,TR,TRAILS,TRL,TRLS:TRL
TRAILER,TRLRS:TRLR
TUNNEL,TUNEL,TUNLS,TUNN,TUNNL,TUNNLS,TUN:TUNL
TURNPIKE,TRNPK,TURNPK:TPKE
UNDERPASS,UNDERPS:UPAS
UNION,UN:UN
UNIONS,UNS:UNS
VALLEY,VALLY,VLLY,VLY:VLY
VALLEYS,VLYS:VLYS
VIADUCT,VDCT,VIA,VIADCT:VIA
VIEW,VW:VW
VIEWS,VWS:VWS
VILLAGE,VILL,VILLAG,VILLG,VILLIAGE,VL:VLG
VILLAGES,VILLGS,VLGS:VLGS
VILLE,VL:VL
VISTA,VIST,VST,VSTA:VIS
WALK,WALKS:WALK
WALL:WALL
WAY,WY:WAY
WAYS:WAYS
WELL,WL:WL
WELLS,WLS:WLS
"""
)

# Publication 28 C2.  The pound sign is deliberately absent: punctuation is
# converted to spaces before this table is applied.
UNIT_DESIGNATORS = _table(
    """
APARTMENT,APT:APT
BASEMENT,BSMT:BSMT
BUILDING,BLDG:BLDG
DEPARTMENT,DEPT:DEPT
FLOOR,FL:FL
FRONT,FRNT:FRNT
HANGER,HNGR:HNGR
KEY:KEY
LOBBY,LBBY:LBBY
LOT:LOT
LOWER,LOWR:LOWR
OFFICE,OFC:OFC
PENTHOUSE,PH:PH
PIER:PIER
REAR:REAR
ROOM,RM:RM
SIDE:SIDE
SLIP:SLIP
SPACE,SPC:SPC
STOP:STOP
SUITE,STE:STE
TRAILER,TRLR:TRLR
UNIT:UNIT
UPPER,UPPR:UPPR
"""
)


def normalize_text(value: str) -> str:
    """Uppercase, replace punctuation with spaces, and collapse whitespace."""
    return " ".join(re.sub(r"[^\w\s]", " ", value.upper()).split())


def normalize_street(value: str) -> str:
    """Apply C1 only at the suffix position and C2 only after that suffix."""
    words = normalize_text(value).split()
    suffix_index = len(words) - 1 if words and words[-1] in STREET_SUFFIXES else -1
    if suffix_index == -1:
        # A suffix can be followed by a C2 designator and its unit detail.
        suffix_index = next(
            (
                index
                for index in range(len(words) - 2, -1, -1)
                if words[index] in STREET_SUFFIXES
                and words[index + 1] in UNIT_DESIGNATORS
            ),
            -1,
        )
    if suffix_index != -1:
        words[suffix_index] = STREET_SUFFIXES[words[suffix_index]]
        if suffix_index + 1 < len(words) and words[suffix_index + 1] in UNIT_DESIGNATORS:
            words[suffix_index + 1] = UNIT_DESIGNATORS[words[suffix_index + 1]]
    return " ".join(words)


def normalize_zip(value: str) -> str:
    """Return ZIP5 when it is present, discarding a ZIP+4 extension."""
    match = re.search(r"\b(\d{5})(?:-\d{4})?\b", value)
    return match.group(1) if match else ""
